project:
  type: website
  output-dir: docs

website:
  title: "Blog Data Science avec R"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/oousmane
      - icon: facebook
        href: https://www.facebook.com/blogdsar/
      - icon: twitter
        href: https://twitter.com/oousmane_11
format:
  html:
    theme: simplex
    css: styles.css

editor: visual

